#!/usr/bin/env bash
# wrapper.sh — Generate runner scripts for scheduled execution
#
# Usage: source wrapper.sh
#
# Functions:
#   schedule_generate_wrapper <id> <repo> <path> <label> — Generate runner script
#
# Environment variables (overridable for testing):
#   CEKERNEL_VAR_DIR — Base directory (default: /usr/local/var/cekernel)

CEKERNEL_VAR_DIR="${CEKERNEL_VAR_DIR:-/usr/local/var/cekernel}"

# Resolve CEKERNEL_DIR from this script's location
_WRAPPER_CEKERNEL_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"

schedule_generate_wrapper() {
  local id="${1:?Usage: schedule_generate_wrapper <id> <repo> <path> <label>}"
  local repo="${2:?Usage: schedule_generate_wrapper <id> <repo> <path> <label>}"
  local captured_path="${3:?Usage: schedule_generate_wrapper <id> <repo> <path> <label>}"
  local label="${4:?Usage: schedule_generate_wrapper <id> <repo> <path> <label>}"

  local runner_dir="${CEKERNEL_VAR_DIR}/runners"
  local runner_file="${runner_dir}/${id}.sh"
  local log_file="${CEKERNEL_VAR_DIR}/logs/schedule.log"

  cat > "$runner_file" <<RUNNER_EOF
#!/usr/bin/env bash
# Generated by: cekernel schedule_generate_wrapper
# ID: ${id}
set -euo pipefail

ID="${id}"
CEKERNEL_DIR="${_WRAPPER_CEKERNEL_DIR}"
CEKERNEL_VAR_DIR="${CEKERNEL_VAR_DIR}"
LOG_FILE="${log_file}"

export PATH="${captured_path}"

# Resolve API key dynamically (env var > OS keychain fallback)
export ANTHROPIC_API_KEY="\${ANTHROPIC_API_KEY:-\$("\${CEKERNEL_DIR}/scripts/scheduler/resolve-api-key.sh" 2>/dev/null)}"

source "\${CEKERNEL_DIR}/scripts/scheduler/registry.sh"

if cd "${repo}" && claude -p \\
  "/dispatch --env headless --label ${label}" >> "\$LOG_FILE" 2>&1; then
  STATUS=0
else
  STATUS=\$?
fi

# Update registry with run status
schedule_registry_update_status "\$ID" "\$( [ "\$STATUS" -eq 0 ] && echo success || echo error )"

# Notify on failure (best-effort, OS-native)
if [ "\$STATUS" -ne 0 ]; then
  case "\$(uname)" in
    Darwin)
      osascript -e "display notification \"Schedule \$ID failed (exit \$STATUS)\" with title \"cekernel\"" 2>/dev/null ;;
    Linux)
      notify-send "cekernel" "Schedule \$ID failed (exit \$STATUS)" 2>/dev/null ;;
  esac
fi

exit \$STATUS
RUNNER_EOF

  chmod 700 "$runner_file"
}
