#!/usr/bin/env bash
# wrapper.sh — Generate runner scripts for scheduled execution
#
# Usage: source wrapper.sh
#
# Functions:
#   schedule_generate_wrapper <id> <repo> <path> <prompt> — Generate runner script
#
# Environment variables (overridable for testing):
#   CEKERNEL_VAR_DIR — Base directory (default: /usr/local/var/cekernel)

CEKERNEL_VAR_DIR="${CEKERNEL_VAR_DIR:-/usr/local/var/cekernel}"

# Resolve CEKERNEL_DIR from this script's location
_WRAPPER_CEKERNEL_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"

schedule_generate_wrapper() {
  local id="${1:?Usage: schedule_generate_wrapper <id> <repo> <path> <prompt>}"
  local repo="${2:?Usage: schedule_generate_wrapper <id> <repo> <path> <prompt>}"
  local captured_path="${3:?Usage: schedule_generate_wrapper <id> <repo> <path> <prompt>}"
  local prompt="${4:?Usage: schedule_generate_wrapper <id> <repo> <path> <prompt>}"

  local runner_dir="${CEKERNEL_VAR_DIR}/runners"
  local runner_file="${runner_dir}/${id}.sh"
  local syslog_file="${CEKERNEL_VAR_DIR}/logs/schedule.log"
  local run_log="${CEKERNEL_VAR_DIR}/logs/${id}.run.log"

  cat > "$runner_file" <<RUNNER_EOF
#!/usr/bin/env bash
# Generated by: cekernel schedule_generate_wrapper
# ID: ${id}
set -euo pipefail

ID="${id}"
CEKERNEL_DIR="${_WRAPPER_CEKERNEL_DIR}"
CEKERNEL_VAR_DIR="${CEKERNEL_VAR_DIR}"
SYSLOG_FILE="${syslog_file}"
RUN_LOG="${run_log}"

export PATH="${captured_path}"

source "\${CEKERNEL_DIR}/scripts/scheduler/registry.sh"
source "\${CEKERNEL_DIR}/scripts/shared/desktop-notify.sh"

# syslog: START
echo "\$(date '+%Y-%m-%dT%H:%M:%S%z') cekernel[\$ID]: START prompt=\"${prompt}\" repo=\"${repo}\"" >> "\$SYSLOG_FILE"
SECONDS=0

if cd "${repo}" && claude -p \\
  "${prompt}" >> "\$RUN_LOG" 2>&1; then
  STATUS=0
else
  STATUS=\$?
fi

# syslog: END
DURATION="\${SECONDS}s"
echo "\$(date '+%Y-%m-%dT%H:%M:%S%z') cekernel[\$ID]: END status=\$( [ "\$STATUS" -eq 0 ] && echo success || echo error ) duration=\$DURATION exit=\$STATUS" >> "\$SYSLOG_FILE"

# Update registry with run status
schedule_registry_update_status "\$ID" "\$( [ "\$STATUS" -eq 0 ] && echo success || echo error )"

# Notify on failure (best-effort, OS-native)
if [ "\$STATUS" -ne 0 ]; then
  desktop_notify "cekernel" "Schedule \$ID failed (exit \$STATUS)"
fi

exit \$STATUS
RUNNER_EOF

  chmod 700 "$runner_file"
}
