#!/usr/bin/env bash
# backends/tmux.sh — tmux backend (ADR-0005 API)
#
# Implements 4 external API functions using tmux.
# Sourced by backend-adapter.sh when CEKERNEL_BACKEND=tmux.
#
# Handle file: ${CEKERNEL_IPC_DIR}/handle-{issue}.{type} contains tmux pane target
# (e.g., "session:window.pane").

# ── External API ──

backend_available() {
  command -v tmux >/dev/null 2>&1 || return 1
  # Verify tmux server is reachable (not just installed)
  tmux list-sessions >/dev/null 2>&1
}

# backend_spawn_worker <issue> <type> <worktree> <prompt>
# Spawns a Worker in a tmux 3-pane layout.
# Saves pane target to handle file internally.
backend_spawn_worker() {
  local issue="$1"
  local type="$2"
  local worktree="$3"
  local prompt="$4"

  # Resolve session (tmux-specific)
  local session=""
  session=$(_backend_resolve_workspace)

  # Spawn main window
  local main_pane
  main_pane=$(_backend_spawn_window "$worktree" "$session")

  # Create right pane (40%) — worker status monitor
  local right_pane
  right_pane=$(_backend_split_pane right 40 "$main_pane" "$worktree" 2>/dev/null) || true
  if [[ -n "$right_pane" ]]; then
    local watch_cmd="watch -n 5 'cat ${CEKERNEL_IPC_DIR}/worker-${issue}.state 2>/dev/null && echo \"---\" && tail -5 ${CEKERNEL_IPC_DIR}/logs/worker-${issue}.log 2>/dev/null'"
    _backend_run_command "$right_pane" "$watch_cmd"
  fi

  # Create bottom pane (25%) — git log
  _backend_split_pane bottom 25 "$main_pane" "$worktree" 2>/dev/null || true

  # Send Claude command to main pane
  # Use double quotes for the prompt to avoid apostrophe/single-quote breakage (#237).
  # Double quotes are safe here: the prompt is generated by spawn-worker.sh and does not
  # contain shell metacharacters that would be interpreted ($, `, \, !, ").
  # Unset CLAUDECODE vars to prevent nested-session detection (#237).
  local claude_cmd="unset CLAUDECODE CLAUDE_CODE_ENTRYPOINT CLAUDE_CODE_SESSION_ACCESS_TOKEN && CEKERNEL_SESSION_ID='${CEKERNEL_SESSION_ID:-}' claude -p --agent ${CEKERNEL_AGENT_WORKER:-worker} \"${prompt}\""
  _backend_run_command "$main_pane" "$claude_cmd"

  # Save handle (pane target)
  echo "$main_pane" > "${CEKERNEL_IPC_DIR}/handle-${issue}.${type}"
}

# backend_get_pid <issue> [type]
# Returns the PID of the process running in the tmux pane.
backend_get_pid() {
  local issue="$1"
  local type="${2:-}"

  local handle_file
  if [[ -n "$type" ]]; then
    handle_file="${CEKERNEL_IPC_DIR}/handle-${issue}.${type}"
  else
    handle_file=$(ls "${CEKERNEL_IPC_DIR}"/handle-"${issue}".* 2>/dev/null | head -1)
  fi

  if [[ -z "$handle_file" || ! -f "$handle_file" ]]; then
    echo "Error: no handle file for issue #${issue}" >&2
    return 1
  fi

  local pane_target
  pane_target=$(cat "$handle_file")
  tmux list-panes -t "$pane_target" -F '#{pane_pid}' 2>/dev/null | head -1
}

# backend_worker_alive <issue> [type]
# exit 0 if alive, exit 1 if dead or no handle
# If type is omitted, checks any handle-{issue}.* file.
backend_worker_alive() {
  local issue="$1"
  local type="${2:-}"

  if [[ -n "$type" ]]; then
    local handle_file="${CEKERNEL_IPC_DIR}/handle-${issue}.${type}"
    [[ -f "$handle_file" ]] || return 1
    local pane_target
    pane_target=$(cat "$handle_file")
    _backend_pane_alive "$pane_target"
  else
    local found=0
    for handle_file in "${CEKERNEL_IPC_DIR}"/handle-"${issue}".*; do
      [[ -f "$handle_file" ]] || continue
      found=1
      local pane_target
      pane_target=$(cat "$handle_file")
      if _backend_pane_alive "$pane_target"; then
        return 0
      fi
    done
    [[ "$found" -eq 1 ]] || return 1
    return 1
  fi
}

# backend_kill_worker <issue> [type]
# Kills the entire window. No error if handle missing.
# If type is omitted, kills all handle-{issue}.* handles.
backend_kill_worker() {
  local issue="$1"
  local type="${2:-}"

  if [[ -n "$type" ]]; then
    local handle_file="${CEKERNEL_IPC_DIR}/handle-${issue}.${type}"
    [[ -f "$handle_file" ]] || return 0
    local pane_target
    pane_target=$(cat "$handle_file")
    _backend_kill_window "$pane_target"
  else
    for handle_file in "${CEKERNEL_IPC_DIR}"/handle-"${issue}".*; do
      [[ -f "$handle_file" ]] || continue
      local pane_target
      pane_target=$(cat "$handle_file")
      _backend_kill_window "$pane_target"
    done
  fi
}

# ── Private API (internal to tmux backend) ──

_backend_resolve_workspace() {
  if [[ -z "${TMUX:-}" ]]; then
    echo ""
    return 0
  fi

  local session
  session=$(tmux display-message -p '#{session_name}' 2>/dev/null) || {
    echo ""
    return 0
  }

  if [[ -z "$session" || "$session" == "null" ]]; then
    echo ""
    return 0
  fi

  echo "$session"
}

# _backend_spawn_window <cwd> [session-name]
# stdout: pane target (session:window.pane)
_backend_spawn_window() {
  local cwd="$1"
  local session="${2:-}"
  local args=()

  if [[ -n "$session" ]]; then
    args+=(-t "$session")
  fi
  args+=(-c "$cwd" -P -F '#{session_name}:#{window_index}.#{pane_index}')

  tmux new-window "${args[@]}"
}

# _backend_run_command <pane-target> <command>
_backend_run_command() {
  local pane_target="$1"
  local cmd="$2"
  tmux send-keys -t "$pane_target" "$cmd" Enter
}

# _backend_split_pane <direction> <percent> <pane-target> <cwd> [command...]
_backend_split_pane() {
  local direction="$1"
  local percent="$2"
  local pane_target="$3"
  local cwd="$4"
  shift 4

  local split_flag
  if [[ "$direction" == "bottom" ]]; then
    split_flag="-v"
  else
    split_flag="-h"
  fi

  local args=(
    "$split_flag" -t "$pane_target"
    -p "$percent"
    -c "$cwd"
    -P -F '#{session_name}:#{window_index}.#{pane_index}'
  )

  if [[ $# -gt 0 ]]; then
    args+=("$@")
  fi

  tmux split-window "${args[@]}"
}

# _backend_pane_alive <pane-target>
_backend_pane_alive() {
  local pane_target="$1"
  tmux list-panes -t "$pane_target" >/dev/null 2>&1
}

# _backend_kill_window <pane-target>
# Kill the entire window that the pane belongs to.
_backend_kill_window() {
  local pane_target="$1"

  # Extract session:window from the pane target
  local window_target
  window_target=$(echo "$pane_target" | sed 's/\.[0-9]*$//')

  tmux kill-window -t "$window_target" 2>/dev/null || true
  echo "Killed window: ${window_target}" >&2
}
