#!/usr/bin/env bash
# spawn.sh — Create worktree + launch process via backend (common spawning logic)
#
# Usage: spawn.sh --agent <type> [--resume] [--priority <priority>] <issue-number> [base-branch]
#   type:     Process type (e.g., worker)
#   priority: critical|high|normal|low or numeric 0-19 (default: normal)
# Output: FIFO path (stdout last line)
# Options:
#   --agent     Process type to spawn (required)
#   --resume    Resume a suspended process (reuse existing worktree)
#   --priority  Set process priority (nice value)
# Exit codes:
#   0 — Process spawned successfully
#   1 — General error
#   2 — Max concurrent processes reached (CEKERNEL_MAX_PROCESSES)
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../shared/load-env.sh"
source "${SCRIPT_DIR}/../shared/session-id.sh"
source "${SCRIPT_DIR}/../shared/claude-json-helper.sh"
source "${SCRIPT_DIR}/../shared/backend-adapter.sh"
source "${SCRIPT_DIR}/../shared/worker-state.sh"
source "${SCRIPT_DIR}/../shared/worker-priority.sh"
source "${SCRIPT_DIR}/../shared/task-file.sh"
source "${SCRIPT_DIR}/../shared/checkpoint-file.sh"
source "${SCRIPT_DIR}/../shared/issue-lock.sh"
source "${SCRIPT_DIR}/../shared/resolve-repo-root.sh"

# ── Flag parsing ──
AGENT_TYPE=""
RESUME=0
PRIORITY="normal"
CUSTOM_PROMPT=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --agent) AGENT_TYPE="${2:?--agent requires a value}"; shift 2 ;;
    --resume) RESUME=1; shift ;;
    --priority) PRIORITY="${2:?--priority requires a value}"; shift 2 ;;
    --prompt) CUSTOM_PROMPT="${2:?--prompt requires a value}"; shift 2 ;;
    *) break ;;
  esac
done

# Validate --agent is provided
if [[ -z "$AGENT_TYPE" ]]; then
  echo "Error: --agent <type> is required" >&2
  echo "Usage: spawn.sh --agent <type> [--resume] [--priority <priority>] <issue-number> [base-branch]" >&2
  exit 1
fi

ISSUE_NUMBER="${1:?Usage: spawn.sh --agent <type> [--resume] [--priority <priority>] <issue-number> [base-branch]}"
BASE_BRANCH="${2:-main}"
REPO_ROOT="$(resolve_repo_root)"

# ── Resolve agent name from environment variable ──
# For type "worker", reads CEKERNEL_AGENT_WORKER (default: "worker")
AGENT_VAR="CEKERNEL_AGENT_$(echo "$AGENT_TYPE" | tr '[:lower:]' '[:upper:]')"
AGENT_NAME="${!AGENT_VAR:-$AGENT_TYPE}"

# ── Concurrency Guard ──
# Priority: CEKERNEL_MAX_WORKERS > CEKERNEL_MAX_PROCESSES > 3
# CEKERNEL_MAX_WORKERS is deprecated; emit warning when used.
if [[ -n "${CEKERNEL_MAX_WORKERS:-}" ]]; then
  echo "Warning: CEKERNEL_MAX_WORKERS is deprecated. Use CEKERNEL_MAX_PROCESSES instead." >&2
  MAX_PROCESSES="${CEKERNEL_MAX_WORKERS}"
else
  MAX_PROCESSES="${CEKERNEL_MAX_PROCESSES:-3}"
fi

active_worker_count() {
  find "$CEKERNEL_IPC_DIR" -maxdepth 1 -name 'worker-*' -type p 2>/dev/null | wc -l | tr -d ' '
}

mkdir -p "$CEKERNEL_IPC_DIR"
ACTIVE=$(active_worker_count)
if [[ "$ACTIVE" -ge "$MAX_PROCESSES" ]]; then
  echo "Error: max processes ($MAX_PROCESSES) reached (active: $ACTIVE). Waiting..." >&2
  exit 2
fi

# ── Issue Lock (duplicate process prevention) ──
if ! issue_lock_acquire "$REPO_ROOT" "$ISSUE_NUMBER"; then
  echo "Error: issue #${ISSUE_NUMBER} is already being processed by another process." >&2
  exit 2
fi

# ── Fetch issue info ──
ISSUE_TITLE=$(gh issue view "$ISSUE_NUMBER" --json title -q '.title')
[[ -n "$ISSUE_TITLE" ]] || { echo "Error: issue #${ISSUE_NUMBER} not found" >&2; exit 1; }

# ── Branch name / path generation ──
# Default naming convention. If the target repository has its own convention,
# the process may rename the branch (cekernel does not enforce branch names).
SLUG=$(echo "$ISSUE_TITLE" \
  | sed 's/[^a-zA-Z0-9]/-/g' \
  | tr '[:upper:]' '[:lower:]' \
  | sed 's/--*/-/g; s/^-//; s/-$//' \
  | cut -c1-40)
BRANCH="issue/${ISSUE_NUMBER}-${SLUG}"
WORKTREE_DIR="${REPO_ROOT}/.worktrees"
WORKTREE="${WORKTREE_DIR}/${BRANCH}"

# ── Rollback: clean up resources on failure ──
rollback() {
  echo "Error: spawn.sh failed. Rolling back..." >&2
  # Kill process via backend (handle file managed internally)
  backend_kill_worker "$ISSUE_NUMBER" "$AGENT_TYPE" 2>/dev/null || true
  rm -f "${CEKERNEL_IPC_DIR}/handle-${ISSUE_NUMBER}.${AGENT_TYPE}"
  # In resume mode, do not destroy the existing worktree/branch
  if [[ "${RESUME:-0}" -eq 0 ]]; then
    # Unregister trust
    if [[ -n "${WORKTREE:-}" && -d "${WORKTREE:-}" ]]; then
      unregister_trust "$WORKTREE" 2>/dev/null || true
    fi
    # Remove worktree
    if [[ -n "${WORKTREE:-}" ]]; then
      git worktree remove --force "$WORKTREE" 2>/dev/null || true
    fi
    # Delete branch
    if [[ -n "${BRANCH:-}" ]]; then
      git branch -D "$BRANCH" 2>/dev/null || true
    fi
  fi
  # Delete payload file (wezterm backend: avoids send-text 1024-byte limit)
  rm -f "${CEKERNEL_IPC_DIR}/payload-${ISSUE_NUMBER}.b64"
  # Delete runner script and prompt file (generated by write_runner_script)
  rm -f "${CEKERNEL_IPC_DIR}/run-${ISSUE_NUMBER}.sh"
  rm -f "${CEKERNEL_IPC_DIR}/prompt-${ISSUE_NUMBER}.txt"
  # Delete log file
  rm -f "${LOG_FILE:-}"
  rmdir "${LOG_DIR:-}" 2>/dev/null || true
  # Delete FIFO, state file, priority file, type file, and backend file
  rm -f "${FIFO:-}"
  rm -f "${CEKERNEL_IPC_DIR}/worker-${ISSUE_NUMBER}.state"
  rm -f "${CEKERNEL_IPC_DIR}/worker-${ISSUE_NUMBER}.priority"
  rm -f "${CEKERNEL_IPC_DIR}/worker-${ISSUE_NUMBER}.type"
  rm -f "${CEKERNEL_IPC_DIR}/worker-${ISSUE_NUMBER}.backend"
  # Release issue lock
  if [[ -n "${REPO_ROOT:-}" ]]; then
    issue_lock_release "$REPO_ROOT" "$ISSUE_NUMBER"
  fi
}
trap rollback ERR

# ── Create FIFO (named pipe) ──
mkdir -p "$CEKERNEL_IPC_DIR"
FIFO="${CEKERNEL_IPC_DIR}/worker-${ISSUE_NUMBER}"
[[ -p "$FIFO" ]] || mkfifo "$FIFO"

# ── State: NEW (Process spawned, worktree being created) ──
worker_state_write "$ISSUE_NUMBER" NEW "spawning"

# ── Priority: Set process nice value ──
worker_priority_write "$ISSUE_NUMBER" "$PRIORITY"

# ── Record process type ──
echo "$AGENT_TYPE" > "${CEKERNEL_IPC_DIR}/worker-${ISSUE_NUMBER}.type"

# ── Record backend name ──
echo "$CEKERNEL_ACTIVE_BACKEND" > "${CEKERNEL_IPC_DIR}/worker-${ISSUE_NUMBER}.backend"

# ── Create log file ──
LOG_DIR="${CEKERNEL_IPC_DIR}/logs"
mkdir -p "$LOG_DIR"
LOG_FILE="${LOG_DIR}/worker-${ISSUE_NUMBER}.log"

# ── Log FIFO creation ──
echo "[$(date -u +%Y-%m-%dT%H:%M:%SZ)] FIFO_CREATE issue=#${ISSUE_NUMBER} path=${FIFO}" >> "$LOG_FILE"

# ── Stale worktree/branch cleanup (retry safety) ──
# If a previous spawn failure + incomplete rollback left stale worktree or branch,
# clean them up before creating new ones.
cleanup_stale_worktree() {
  local worktree="$1" branch="$2"
  # Registered as git worktree (.git file holds worktree reference)
  if [[ -f "${worktree}/.git" ]]; then
    echo "Warning: stale worktree found at ${worktree}, removing..." >&2
    git worktree remove --force "$worktree" 2>/dev/null || true
  fi
  # Not registered in git worktree list, but directory still exists
  if [[ -d "$worktree" ]]; then
    echo "Warning: orphaned worktree directory found at ${worktree}, removing..." >&2
    rm -rf "$worktree"
    git worktree prune 2>/dev/null || true
  fi
  # Delete stale branch
  if git rev-parse --verify "$branch" >/dev/null 2>&1; then
    echo "Warning: stale branch found: ${branch}, deleting..." >&2
    git branch -D "$branch" 2>/dev/null || true
  fi
}

# ── Create or reuse worktree ──
if [[ "$RESUME" -eq 1 ]]; then
  # Resume mode: reuse existing worktree (must already exist)
  if [[ ! -d "$WORKTREE" ]]; then
    echo "Error: worktree not found for resume: ${WORKTREE}" >&2
    echo "Cannot resume without an existing worktree." >&2
    exit 1
  fi
  echo "resume: reusing worktree $WORKTREE" >&2

  # Re-register trust (may have been cleaned up)
  register_trust "$WORKTREE"

  # NOTE: Resume markers (## Resume Reason: ...) are NOT cleared here.
  # The Worker reads the marker to determine its startup mode, then clears
  # it as self-cleanup. Clearing here would race with the Orchestrator's
  # marker write and prevent the Worker from entering the correct mode.

  # Verify checkpoint exists for resume
  if checkpoint_file_exists "$WORKTREE"; then
    echo "checkpoint: $(checkpoint_file_path "$WORKTREE")" >&2
  else
    echo "Warning: no checkpoint file found. Process will start fresh." >&2
  fi
else
  # Normal mode: create new worktree
  mkdir -p "$WORKTREE_DIR"
  git fetch origin "${BASE_BRANCH}" --quiet
  cleanup_stale_worktree "$WORKTREE" "$BRANCH"
  git worktree add -b "$BRANCH" "$WORKTREE" "origin/${BASE_BRANCH}"

  # Register trust (so process can start without trust prompt)
  register_trust "$WORKTREE"

  # Extract issue data into worktree (session memory: page cache)
  # Processes read .cekernel-task.md locally instead of calling gh issue view,
  # reducing GitHub API calls and context window consumption.
  create_task_file "$WORKTREE" "$ISSUE_NUMBER"
  echo "task file: $(task_file_path "$WORKTREE")" >&2
fi

echo "worktree: $WORKTREE" >&2
echo "branch:   $BRANCH" >&2

# ── Compute cekernel script paths for process PATH ──
CEKERNEL_WORKER_SCRIPTS="$(cd "${SCRIPT_DIR}/../process" && pwd)"
CEKERNEL_SHARED_SCRIPTS="$(cd "${SCRIPT_DIR}/../shared" && pwd)"

# ── Write .cekernel-env to worktree ──
# Instead of embedding a 200+ char export string in the prompt (which LLMs
# can truncate, losing :$PATH and breaking basic commands like wc/grep),
# write env vars to a file and use a short "source .cekernel-env" prefix.
cat > "${WORKTREE}/.cekernel-env" <<EOF
export CEKERNEL_SESSION_ID=${CEKERNEL_SESSION_ID}
export CEKERNEL_IPC_DIR=${CEKERNEL_IPC_DIR}
export CEKERNEL_ENV=${CEKERNEL_ENV}
export PATH=${CEKERNEL_WORKER_SCRIPTS}:${CEKERNEL_SHARED_SCRIPTS}:\$PATH
EOF

# ── Launch process via backend ──
# If --prompt was provided, use it. Otherwise, use the default Worker prompt.
# PATH and env vars are propagated via .cekernel-env sourced by the runner script.
if [[ -n "$CUSTOM_PROMPT" ]]; then
  PROMPT="${CUSTOM_PROMPT}"
elif [[ "$RESUME" -eq 1 ]]; then
  PROMPT="Resume issue #${ISSUE_NUMBER}. Read .cekernel-checkpoint.md to understand previous progress, then continue from where the previous Worker left off. First read the target repository's CLAUDE.md and fully follow its conventions. Follow only the kernel Worker Protocol for lifecycle: implement → create PR → verify CI. When done, run notify-complete.sh ${ISSUE_NUMBER} ci-passed <pr-number>."
else
  PROMPT="Resolve issue #${ISSUE_NUMBER}. First read the target repository's CLAUDE.md and fully follow its conventions. Follow only the kernel Worker Protocol for lifecycle: implement → create PR → verify CI. When done, run notify-complete.sh ${ISSUE_NUMBER} ci-passed <pr-number>."
fi

# Backend handles workspace resolution, window spawning, and handle file management internally.
# Callers pass (issue, type, worktree, prompt, agent-name) — the backend decides how to launch.
backend_spawn_worker "$ISSUE_NUMBER" "$AGENT_TYPE" "$WORKTREE" "$PROMPT" "$AGENT_NAME"

# ── Update lock PID with the real process PID ──
# spawn.sh ($$) is short-lived and exits after launching the process.
# Without this update, stale detection (kill -0) would always see a dead PID,
# causing false stale-lock recovery and potential duplicate spawns.
BACKEND_PID=$(backend_get_pid "$ISSUE_NUMBER" "$AGENT_TYPE" 2>/dev/null) || true
if [[ -n "$BACKEND_PID" && "$BACKEND_PID" != "null" ]]; then
  issue_lock_update_pid "$REPO_ROOT" "$ISSUE_NUMBER" "$BACKEND_PID"
fi

# ── State: READY (Worktree ready, Claude agent starting) ──
worker_state_write "$ISSUE_NUMBER" READY "agent-starting"

# ── Record spawn marker (.spawned file) ──
# Persists across cleanup for post-mortem transcript discovery.
# transcript-locator.sh scans these to reverse-lookup which session handled an issue.
# Also stores the epoch timestamp used for uptime calculation.
date +%s > "${CEKERNEL_IPC_DIR}/${AGENT_TYPE}-${ISSUE_NUMBER}.spawned"

# ── Record lifecycle event in log ──
if [[ "$RESUME" -eq 1 ]]; then
  echo "[$(date -u +%Y-%m-%dT%H:%M:%SZ)] RESUME issue=#${ISSUE_NUMBER} branch=${BRANCH} priority=${PRIORITY} type=${AGENT_TYPE}" >> "$LOG_FILE"
  echo "session: $CEKERNEL_SESSION_ID" >&2
  echo "${AGENT_TYPE} resumed: issue #${ISSUE_NUMBER}" >&2
else
  echo "[$(date -u +%Y-%m-%dT%H:%M:%SZ)] SPAWN issue=#${ISSUE_NUMBER} branch=${BRANCH} priority=${PRIORITY} type=${AGENT_TYPE}" >> "$LOG_FILE"
  echo "session: $CEKERNEL_SESSION_ID" >&2
  echo "${AGENT_TYPE} spawned: issue #${ISSUE_NUMBER}" >&2
fi

# Return FIFO path (used by orchestrator for reading)
echo "$FIFO"
